version: "3.9"

services:
  crypter:
    image: crypter:latest
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypter
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d crypter"]
      interval: 5s
      timeout: 5s
      retries: 5
