// Code generated by MockGen. DO NOT EDIT.
// Source: internal/keys/service/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/keys/service/service.go -destination=./mocks/keys_service_mock.go -package=mocks KeysService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/ObscuraNote/api-general/internal/keys/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockKeysRepository is a mock of KeysRepository interface.
type MockKeysRepository struct {
	ctrl     *gomock.Controller
	recorder *MockKeysRepositoryMockRecorder
	isgomock struct{}
}

// MockKeysRepositoryMockRecorder is the mock recorder for MockKeysRepository.
type MockKeysRepositoryMockRecorder struct {
	mock *MockKeysRepository
}

// NewMockKeysRepository creates a new mock instance.
func NewMockKeysRepository(ctrl *gomock.Controller) *MockKeysRepository {
	mock := &MockKeysRepository{ctrl: ctrl}
	mock.recorder = &MockKeysRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeysRepository) EXPECT() *MockKeysRepositoryMockRecorder {
	return m.recorder
}

// AddKey mocks base method.
func (m *MockKeysRepository) AddKey(userId int64, note dto.KeyImput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddKey", userId, note)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddKey indicates an expected call of AddKey.
func (mr *MockKeysRepositoryMockRecorder) AddKey(userId, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddKey", reflect.TypeOf((*MockKeysRepository)(nil).AddKey), userId, note)
}

// DeleteKey mocks base method.
func (m *MockKeysRepository) DeleteKey(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKey", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKey indicates an expected call of DeleteKey.
func (mr *MockKeysRepositoryMockRecorder) DeleteKey(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKey", reflect.TypeOf((*MockKeysRepository)(nil).DeleteKey), id)
}

// GetKeysByUser mocks base method.
func (m *MockKeysRepository) GetKeysByUser(userId int64) ([]dto.KeyOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeysByUser", userId)
	ret0, _ := ret[0].([]dto.KeyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeysByUser indicates an expected call of GetKeysByUser.
func (mr *MockKeysRepositoryMockRecorder) GetKeysByUser(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeysByUser", reflect.TypeOf((*MockKeysRepository)(nil).GetKeysByUser), userId)
}

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// CheckUserExists mocks base method.
func (m *MockUserService) CheckUserExists(userAddress, password string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserExists", userAddress, password)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserExists indicates an expected call of CheckUserExists.
func (mr *MockUserServiceMockRecorder) CheckUserExists(userAddress, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserExists", reflect.TypeOf((*MockUserService)(nil).CheckUserExists), userAddress, password)
}

// CreateUser mocks base method.
func (m *MockUserService) CreateUser(userAddress, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", userAddress, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserServiceMockRecorder) CreateUser(userAddress, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserService)(nil).CreateUser), userAddress, password)
}

// DeleteUser mocks base method.
func (m *MockUserService) DeleteUser(userAddress string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", userAddress)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserServiceMockRecorder) DeleteUser(userAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserService)(nil).DeleteUser), userAddress)
}

// GetUserId mocks base method.
func (m *MockUserService) GetUserId(userAddress, password string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserId", userAddress, password)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserId indicates an expected call of GetUserId.
func (mr *MockUserServiceMockRecorder) GetUserId(userAddress, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserId", reflect.TypeOf((*MockUserService)(nil).GetUserId), userAddress, password)
}

// UpdatePassword mocks base method.
func (m *MockUserService) UpdatePassword(userAddress, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", userAddress, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockUserServiceMockRecorder) UpdatePassword(userAddress, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserService)(nil).UpdatePassword), userAddress, password)
}
