// Code generated by MockGen. DO NOT EDIT.
// Source: internal/keys/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/keys/repository/repository.go -destination=./mocks/keys_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/ObscuraNote/api-general/internal/keys/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockKeysRepository is a mock of KeysRepository interface.
type MockKeysRepository struct {
	ctrl     *gomock.Controller
	recorder *MockKeysRepositoryMockRecorder
	isgomock struct{}
}

// MockKeysRepositoryMockRecorder is the mock recorder for MockKeysRepository.
type MockKeysRepositoryMockRecorder struct {
	mock *MockKeysRepository
}

// NewMockKeysRepository creates a new mock instance.
func NewMockKeysRepository(ctrl *gomock.Controller) *MockKeysRepository {
	mock := &MockKeysRepository{ctrl: ctrl}
	mock.recorder = &MockKeysRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeysRepository) EXPECT() *MockKeysRepositoryMockRecorder {
	return m.recorder
}

// AddKey mocks base method.
func (m *MockKeysRepository) AddKey(userId int64, note dto.KeyImput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddKey", userId, note)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddKey indicates an expected call of AddKey.
func (mr *MockKeysRepositoryMockRecorder) AddKey(userId, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddKey", reflect.TypeOf((*MockKeysRepository)(nil).AddKey), userId, note)
}

// DeleteKey mocks base method.
func (m *MockKeysRepository) DeleteKey(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKey", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKey indicates an expected call of DeleteKey.
func (mr *MockKeysRepositoryMockRecorder) DeleteKey(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKey", reflect.TypeOf((*MockKeysRepository)(nil).DeleteKey), id)
}

// GetKeysByUser mocks base method.
func (m *MockKeysRepository) GetKeysByUser(userId int64) ([]dto.KeyOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeysByUser", userId)
	ret0, _ := ret[0].([]dto.KeyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeysByUser indicates an expected call of GetKeysByUser.
func (mr *MockKeysRepositoryMockRecorder) GetKeysByUser(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeysByUser", reflect.TypeOf((*MockKeysRepository)(nil).GetKeysByUser), userId)
}
